/*
 *  ======== ti_log_config.c ========
 *  Configured  module definitions for ti.log
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool.
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "ti_log_config.h"

#ifndef ti_log_Log_ENABLE
    #warning "Symbol ti_log_Log_ENABLE must be defined to use logging."
#endif // ti_log_Log_ENABLE


/*
 *  ======== Log Modules ========
 */
Log_MODULE_DEFINE(LogModule_Zigbee_Low_Level_MAC, Log_MODULE_INIT_SINK_BUF(CONFIG_ti_log_LogSinkBuf_0, 0, LogSinkBuf_printfSingleton, LogSinkBuf_bufDepInjection, NULL));

Log_MODULE_DEFINE(LogModule_Zigbee_App, Log_MODULE_INIT_SINK_BUF(CONFIG_ti_log_LogSinkBuf_0, Log_DEBUG | Log_VERBOSE | Log_INFO | Log_WARNING | Log_ERROR, LogSinkBuf_printfSingleton, LogSinkBuf_bufDepInjection, NULL));



/*
 *  ======== LogSinkBuf ========
 */
#include <ti/log/LogSinkBuf.h>

Log_SINK_BUF_DEFINE(CONFIG_ti_log_LogSinkBuf_0, LogSinkBuf_Type_CIRCULAR, 100);

