/*
 *  ======== ti_log_config.h ========
 *  Configured module declarations for the TI logger
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool.
 */
#ifndef ti_log_config_h
#define ti_log_config_h

#ifdef __cplusplus
extern "C" {
#endif


/*
 *  ======== Log Modules ========
 */
#include <ti/log/Log.h>

Log_MODULE_USE(LogModule_Zigbee_App);



/*
 *  ======== LogSinkBuf ========
 */
#include <ti/log/LogSinkBuf.h>

Log_SINK_BUF_USE(CONFIG_ti_log_LogSinkBuf_0);


#ifdef __cplusplus
}
#endif

#endif /* include guard */
