/*
 *  ======== rov.js ========
 *  Component configuration meta-data
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool.
 */

/*
 *  ======== ti_log/LogSinkBuf ========
 */

var LogSinkBuf_settings = {
    count: 1
};

